#!/usr/bin/expect -f
# set qemu_bin [lindex $argv 0];
# set qemu_arg [lrange $argv 1 end];
set timeout 60
spawn {*}$argv
set bin_name [lindex $argv 0];
set sleep_time 0

proc test_cmd {file_name num} {
#    upvar 2 $sleep_time sleep_time
    # expect "\[1m\[32mNPUCore\[0m:\[1m\[34m/\[0m#"
    expect " \[1m \[32mNPUCore \[0m: \[1m \[34m/ \[0m#"
    sleep $num
    send $file_name
}

if  { $bin_name != "qemu-system-riscv64" } {
    expect {
        "Device(s) found" {
            send "c"
        }
        timeout {
            puts "Timeout waiting for Device(s) found"
            exit 1
        }
    }
    expect {
        "=>" {
            send "tftpboot uImage\n"
        }
        timeout {
            puts "Timeout waiting for u-boot prompt"
            exit 1
        }
    }
    expect {
        "=>" {
            send "bootm\n"
        }
        timeout {
            puts "Timeout waiting for u-boot prompt after tftpboot"
            exit 1
        }
    }
}

# test_cmd "lua_testcode.sh\n" $sleep_time
# test_cmd "busybox_testcode.sh\n" $sleep_time
# test_cmd "lmbench_testcode.sh\n" $sleep_time

# expect "\[1m\[32mNPUCore\[0m:\[1m\[34m/\[0m#"
# sleep 3
# send "lua_testcode.sh\n"
# expect "\[1m\[32mNPUCore\[0m:\[1m\[34m/\[0m#"
# sleep 3
# send "busybox_testcode.sh\n"
# expect "\[1m\[32mNPUCore\[0m:\[1m\[34m/\[0m#"
# sleep 3
# send "lmbench_testcode.sh\n"
# send "while true; do lmbench_testcode.sh; echo \"hi\";done\r"
interact
